version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 408420567631.dkr.ecr.ap-southeast-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker images...

      - docker build -t dou-back-service .
      - docker tag dou-back-service:latest 408420567631.dkr.ecr.ap-southeast-1.amazonaws.com/dou-back-service:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 408420567631.dkr.ecr.ap-southeast-1.amazonaws.com/dou-back-service:latest
