name: API Workflow

on:
  workflow_dispatch:

jobs:
  BuildAndDeploy:
    runs-on: ubuntu-lastest
    steps:
      - name: get code
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Generate
        run: npm run generate

      - name: Build
        run: npm run build

      - name: Copy font to artifact
        run: |
          mkdir -p dist/assets
          cp -r src/assets/my-fonts dist/assets/my-fonts

      - name: Create procfile
        run: |
          touch Procfile
          echo "web: node ./dist/main" > Procfile

      - name: Generate deployment package
        run: zip -r artifact.zip dist prisma package.json yarn.lock .npmrc .yarnrc .platform Procfile -x '*node_modules*'

      - name: Deploy to Elasticbeanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{env.APP_NAME}}-app
          environment_name: ${{env.APP_NAME}}-env
          version_label: ${{env.APP_NAME}}-${{ github.sha }}
          region: ap-southeast-1
          deployment_package: artifact.zip
          use_existing_version_if_available: true
